# Generated by Django 3.2.12 on 2022-03-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='last_name',
        ),
    ]
