# Generated by Django 3.2.12 on 2022-03-07 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_at',
            new_name='check_in_time',
        ),
    ]
