# Generated by Django 3.2.12 on 2022-03-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_created_at_task_check_in_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='e_mail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
