# Generated by Django 3.2.12 on 2022-03-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_e_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='major',
            field=models.TextField(blank=True, null=True),
        ),
    ]
