# Generated by Django 3.2.12 on 2022-03-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='count',
            field=models.TextField(blank=True, null=True),
        ),
    ]
